dataset: CUB
dataroot: ./data

image_embedding: res101
class_embedding: sent
syn_num: 100

gpus: 0
cuda: True
gzsl: True
save_model: False

manualSeed: 415
attSize: 1024
resSize: 2048
embedSize: 2048
nclass_all: 200
nclass_seen: 150

# gan
batch_size: 1024
nepoch: 1000
lr: 0.0001
lr_dec_rate: 0.99
lr_decay_epoch: 100
beta1: 0.5
nz: 1024
ngh: 4096
ndh: 4096
critic_iter: 5

# gp
lambda1: 10

# classifier
batch_cls: 128
cls_nepoch: 25
classifier_lr: 0.001

# circle loss
m: 0.25
gamma: 128